[package]
name = "tuiznos"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["crossterm"] }
tui-textarea = { version = "0.7.0", features = ["search"] }
color-eyre = "0.6.5"
crossterm = "0.28.1"
